In [11]:
import tushare as ts
import pandas as pd
ts

In [3]:
df = ts.get_k_data(code='600519', start='1990-01-01')
df

本接口即将停止更新，请尽快使用Pro版接口：https://waditu.com/document/2

            date      open     close      high       low     volume    code
0     2001-08-27     5.392     5.554     5.902     5.132  406318.00  600519
1     2001-08-28     5.467     5.759     5.781     5.407  129647.79  600519
2     2001-08-29     5.777     5.684     5.781     5.640   53252.75  600519
3     2001-08-30     5.668     5.796     5.860     5.624   48013.06  600519
4     2001-08-31     5.804     5.782     5.877     5.749   23231.48  600519
5     2001-09-03     5.812     5.779     5.870     5.757   22112.09  600519
6     2001-09-04     5.782     5.852     5.949     5.762   37006.77  600519
7     2001-09-05     5.876     5.849     5.924     5.813   26066.95  600519
8     2001-09-06     5.835     5.734     5.854     5.704   28997.03  600519
9     2001-09-07     5.702     5.574     5.773     5.570   31552.25  600519
10    2001-09-10     5.531     5.734     5.757     5.470   18878.89  600519
11    2001-09-11     5.749     5.670     5.773     5.656   11390.81  600519
12    2001-09-12     5.520     5.621     5.656     5.515   25045.19  600519
13    2001-09-13     5.626     5.607     5.671     5.577   10986.68  600519
14    2001-09-14     5.626     5.671     5.702     5.593    7672.83  600519
15    2001-09-17     5.637     5.599     5.670     5.546    8983.97  600519
16    2001-09-18     5.606     5.663     5.710     5.601   10773.26  600519
17    2001-09-19     5.671     5.768     5.768     5.634    8650.53  600519
18    2001-09-20     5.765     5.720     5.788     5.702   11173.35  600519
19    2001-09-21     5.668     5.634     5.718     5.624    7879.72  600519
20    2001-09-24     5.634     5.632     5.685     5.624    4068.60  600519
21    2001-09-25     5.668     5.660     5.709     5.632    3488.45  600519
22    2001-09-26     5.642     5.637     5.699     5.624    4956.26  600519
23    2001-09-27     5.637     5.734     5.777     5.624    8778.04  600519
24    2001-09-28     5.765     5.795     5.812     5.702   17088.47  600519
25    2001-10-08     5.781     5.715     5.809     5.663    6552.17  600519
26    2001-10-09     5.718     5.827     5.859     5.718    9558.52  600519
27    2001-10-10     5.827     5.640     5.848     5.629   17548.69  600519
28    2001-10-11     5.626     5.585     5.702     5.570   12306.84  600519
29    2001-10-12     5.609     5.624     5.726     5.320   20010.70  600519
...          ...       ...       ...       ...       ...        ...     ...
4751  2021-07-19  1955.890  1975.000  1986.000  1941.000   30052.00  600519
4752  2021-07-20  1975.000  1980.000  1988.930  1961.410   23475.00  600519
4753  2021-07-21  1989.000  1969.000  2006.000  1962.010   29780.00  600519
4754  2021-07-22  1960.000  1940.010  1973.900  1938.960   39090.00  600519
4755  2021-07-23  1937.820  1900.000  1937.820  1895.090   47585.00  600519
4756  2021-07-26  1879.000  1804.110  1879.000  1780.000   98619.00  600519
4757  2021-07-27  1803.000  1712.890  1810.000  1703.000   86577.00  600519
4758  2021-07-28  1703.000  1768.900  1788.200  1682.120   85369.00  600519
4759  2021-07-29  1810.010  1749.790  1823.000  1734.340   63864.00  600519
4760  2021-07-30  1725.000  1678.990  1725.000  1657.760   77736.00  600519
4761  2021-08-02  1664.000  1755.000  1755.980  1620.720   97401.00  600519
4762  2021-08-03  1730.000  1749.300  1768.990  1688.800   54375.00  600519
4763  2021-08-04  1734.060  1724.000  1760.000  1718.000   38175.00  600519
4764  2021-08-05  1692.880  1699.000  1745.000  1676.360   48060.00  600519
4765  2021-08-06  1689.000  1671.000  1694.010  1646.600   45686.00  600519
4766  2021-08-09  1651.000  1693.800  1709.000  1650.000   47698.00  600519
4767  2021-08-10  1700.000  1799.000  1802.880  1675.000   83285.00  600519
4768  2021-08-11  1780.010  1750.500  1785.010  1750.010   38663.00  600519
4769  2021-08-12  1732.000  1690.000  1749.000  1686.190   47551.00  600519
4770  2021-08-13  1690.000  1700.040  1713.000  1679.000   37905.00  600519
4771  2021-08-16  1696.000  1699.200  1713.600  1685.080   28057.00  600519
4772  2021-08-17  1700.000  1635.000  1700.000  1628.880   61201.00  600519
4773  2021-08-18  1624.660  1620.000  1642.990  1600.000   59970.00  600519
4774  2021-08-19  1622.220  1619.970  1643.200  1600.000   41292.00  600519
4775  2021-08-20  1555.170  1548.000  1597.550  1525.500  114545.00  600519
4776  2021-08-23  1537.880  1570.190  1599.000  1536.770   71597.00  600519
4777  2021-08-24  1575.000  1625.180  1642.550  1565.770   72594.00  600519
4778  2021-08-25  1647.640  1665.020  1680.870  1643.000   54239.00  600519
4779  2021-08-26  1664.990  1595.000  1664.990  1594.720   54020.00  600519
4780  2021-08-27  1589.000  1596.030  1625.000  1584.100   36095.00  600519

[4781 rows x 7 columns]

## 对数据进行预处理

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4781 entries, 0 to 4780
Data columns (total 7 columns):
date      4781 non-null object
open      4781 non-null float64
close     4781 non-null float64
high      4781 non-null float64
low       4781 non-null float64
volume    4781 non-null float64
code      4781 non-null object
dtypes: float64(5), object(2)
memory usage: 298.8+ KB

In [37]:
### 将df中的数据存储到本地
df.to_csv('./maotai.csv')

In [38]:
df = pd.read_csv('./maotai.csv')
df

,Unnamed: 0,date,open,close,high,low,volume,code
0,0,2001-08-27,5.392,5.554,5.902,5.132,406318.00,600519
1,1,2001-08-28,5.467,5.759,5.781,5.407,129647.79,600519
2,2,2001-08-29,5.777,5.684,5.781,5.640,53252.75,600519
3,3,2001-08-30,5.668,5.796,5.860,5.624,48013.06,600519
4,4,2001-08-31,5.804,5.782,5.877,5.749,23231.48,600519
5,5,2001-09-03,5.812,5.779,5.870,5.757,22112.09,600519
6,6,2001-09-04,5.782,5.852,5.949,5.762,37006.77,600519
7,7,2001-09-05,5.876,5.849,5.924,5.813,26066.95,600519
8,8,2001-09-06,5.835,5.734,5.854,5.704,28997.03,600519
9,9,2001-09-07,5.702,5.574,5.773,5.570,31552.25,600519
10,10,2001-09-10,5.531,5.734,5.757,5.470,18878.89,600519
11,11,2001-09-11,5.749,5.670,5.773,5.656,11390.81,600519
12,12,2001-09-12,5.520,5.621,5.656,5.515,25045.19,600519
13,13,2001-09-13,5.626,5.607,5.671,5.577,10986.68,600519
14,14,2001-09-14,5.626,5.671,5.702,5.593,7672.83,600519
15,15,2001-09-17,5.637,5.599,5.670,5.546,8983.97,600519
16,16,2001-09-18,5.606,5.663,5.710,5.601,10773.26,600519
17,17,2001-09-19,5.671,5.768,5.768,5.634,8650.53,600519
18,18,2001-09-20,5.765,5.720,5.788,5.702,11173.35,600519
19,19,2001-09-21,5.668,5.634,5.718,5.624,7879.72,600519
20,20,2001-09-24,5.634,5.632,5.685,5.624,4068.60,600519
21,21,2001-09-25,5.668,5.660,5.709,5.632,3488.45,600519
22,22,2001-09-26,5.642,5.637,5.699,5.624,4956.26,600519
23,23,2001-09-27,5.637,5.734,5.777,5.624,8778.04,600519
24,24,2001-09-28,5.765,5.795,5.812,5.702,17088.47,600519
25,25,2001-10-08,5.781,5.715,5.809,5.663,6552.17,600519
26,26,2001-10-09,5.718,5.827,5.859,5.718,9558.52,600519
27,27,2001-10-10,5.827,5.640,5.848,5.629,17548.69,600519
28,28,2001-10-11,5.626,5.585,5.702,5.570,12306.84,600519
29,29,2001-10-12,5.609,5.624,5.726,5.320,20010.70,600519
...,...,...,...,...,...,...,...,...
4751,4751,2021-07-19,1955.890,1975.000,1986.000,1941.000,30052.00,600519
4752,4752,2021-07-20,1975.000,1980.000,1988.930,1961.410,23475.00,600519
4753,4753,2021-07-21,1989.000,1969.000,2006.000,1962.010,29780.00,600519
4754,4754,2021-07-22,1960.000,1940.010,1973.900,1938.960,39090.00,600519
4755,4755,2021-07-23,1937.820,1900.000,1937.820,1895.090,47585.00,600519
4756,4756,2021-07-26,1879.000,1804.110,1879.000,1780.000,98619.00,600519
4757,4757,2021-07-27,1803.000,1712.890,1810.000,1703.000,86577.00,600519
4758,4758,2021-07-28,1703.000,1768.900,1788.200,1682.120,85369.00,600519
4759,4759,2021-07-29,1810.010,1749.790,1823.000,1734.340,63864.00,600519
4760,4760,2021-07-30,1725.000,1678.990,1725.000,1657.760,77736.00,600519
4761,4761,2021-08-02,1664.000,1755.000,1755.980,1620.720,97401.00,600519
4762,4762,2021-08-03,1730.000,1749.300,1768.990,1688.800,54375.00,600519
4763,4763,2021-08-04,1734.060,1724.000,1760.000,1718.000,38175.00,600519
4764,4764,2021-08-05,1692.880,1699.000,1745.000,1676.360,48060.00,600519
4765,4765,2021-08-06,1689.000,1671.000,1694.010,1646.600,45686.00,600519
4766,4766,2021-08-09,1651.000,1693.800,1709.000,1650.000,47698.00,600519
4767,4767,2021-08-10,1700.000,1799.000,1802.880,1675.000,83285.00,600519
4768,4768,2021-08-11,1780.010,1750.500,1785.010,1750.010,38663.00,600519
4769,4769,2021-08-12,1732.000,1690.000,1749.000,1686.190,47551.00,600519
4770,4770,2021-08-13,1690.000,1700.040,1713.000,1679.000,37905.00,600519
4771,4771,2021-08-16,1696.000,1699.200,1713.600,1685.080,28057.00,600519
4772,4772,2021-08-17,1700.000,1635.000,1700.000,1628.880,61201.00,600519
4773,4773,2021-08-18,1624.660,1620.000,1642.990,1600.000,59970.00,600519
4774,4774,2021-08-19,1622.220,1619.970,1643.200,1600.000,41292.00,600519
4775,4775,2021-08-20,1555.170,1548.000,1597.550,1525.500,114545.00,600519
4776,4776,2021-08-23,1537.880,1570.190,1599.000,1536.770,71597.00,600519
4777,4777,2021-08-24,1575.000,1625.180,1642.550,1565.770,72594.00,600519
4778,4778,2021-08-25,1647.640,1665.020,1680.870,1643.000,54239.00,600519
4779,4779,2021-08-26,1664.990,1595.000,1664.990,1594.720,54020.00,600519
4780,4780,2021-08-27,1589.000,1596.030,1625.000,1584.100,36095.00,600519

In [39]:
# 删除指定列
df.drop(labels='Unnamed: 0', axis=1, inplace=True)# axis=0表示行

In [40]:
df['date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4781 entries, 0 to 4780
Data columns (total 7 columns):
date      4781 non-null datetime64[ns]
open      4781 non-null float64
close     4781 non-null float64
high      4781 non-null float64
low       4781 non-null float64
volume    4781 non-null float64
code      4781 non-null int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 261.5 KB

In [41]:
# 将date作为源数据的行索引
df.set_index('date', inplace=True)

In [34]:
df

           date      open     close      high       low     volume    code
0    2001-08-27     5.392     5.554     5.902     5.132  406318.00  600519
1    2001-08-28     5.467     5.759     5.781     5.407  129647.79  600519
2    2001-08-29     5.777     5.684     5.781     5.640   53252.75  600519
3    2001-08-30     5.668     5.796     5.860     5.624   48013.06  600519
4    2001-08-31     5.804     5.782     5.877     5.749   23231.48  600519
5    2001-09-03     5.812     5.779     5.870     5.757   22112.09  600519
6    2001-09-04     5.782     5.852     5.949     5.762   37006.77  600519
7    2001-09-05     5.876     5.849     5.924     5.813   26066.95  600519
8    2001-09-06     5.835     5.734     5.854     5.704   28997.03  600519
9    2001-09-07     5.702     5.574     5.773     5.570   31552.25  600519
10   2001-09-10     5.531     5.734     5.757     5.470   18878.89  600519
11   2001-09-11     5.749     5.670     5.773     5.656   11390.81  600519
12   2001-09-12     5.520     5.621     5.656     5.515   25045.19  600519
13   2001-09-13     5.626     5.607     5.671     5.577   10986.68  600519
14   2001-09-14     5.626     5.671     5.702     5.593    7672.83  600519
15   2001-09-17     5.637     5.599     5.670     5.546    8983.97  600519
16   2001-09-18     5.606     5.663     5.710     5.601   10773.26  600519
17   2001-09-19     5.671     5.768     5.768     5.634    8650.53  600519
18   2001-09-20     5.765     5.720     5.788     5.702   11173.35  600519
19   2001-09-21     5.668     5.634     5.718     5.624    7879.72  600519
20   2001-09-24     5.634     5.632     5.685     5.624    4068.60  600519
21   2001-09-25     5.668     5.660     5.709     5.632    3488.45  600519
22   2001-09-26     5.642     5.637     5.699     5.624    4956.26  600519
23   2001-09-27     5.637     5.734     5.777     5.624    8778.04  600519
24   2001-09-28     5.765     5.795     5.812     5.702   17088.47  600519
25   2001-10-08     5.781     5.715     5.809     5.663    6552.17  600519
26   2001-10-09     5.718     5.827     5.859     5.718    9558.52  600519
27   2001-10-10     5.827     5.640     5.848     5.629   17548.69  600519
28   2001-10-11     5.626     5.585     5.702     5.570   12306.84  600519
29   2001-10-12     5.609     5.624     5.726     5.320   20010.70  600519
...         ...       ...       ...       ...       ...        ...     ...
4751 2021-07-19  1955.890  1975.000  1986.000  1941.000   30052.00  600519
4752 2021-07-20  1975.000  1980.000  1988.930  1961.410   23475.00  600519
4753 2021-07-21  1989.000  1969.000  2006.000  1962.010   29780.00  600519
4754 2021-07-22  1960.000  1940.010  1973.900  1938.960   39090.00  600519
4755 2021-07-23  1937.820  1900.000  1937.820  1895.090   47585.00  600519
4756 2021-07-26  1879.000  1804.110  1879.000  1780.000   98619.00  600519
4757 2021-07-27  1803.000  1712.890  1810.000  1703.000   86577.00  600519
4758 2021-07-28  1703.000  1768.900  1788.200  1682.120   85369.00  600519
4759 2021-07-29  1810.010  1749.790  1823.000  1734.340   63864.00  600519
4760 2021-07-30  1725.000  1678.990  1725.000  1657.760   77736.00  600519
4761 2021-08-02  1664.000  1755.000  1755.980  1620.720   97401.00  600519
4762 2021-08-03  1730.000  1749.300  1768.990  1688.800   54375.00  600519
4763 2021-08-04  1734.060  1724.000  1760.000  1718.000   38175.00  600519
4764 2021-08-05  1692.880  1699.000  1745.000  1676.360   48060.00  600519
4765 2021-08-06  1689.000  1671.000  1694.010  1646.600   45686.00  600519
4766 2021-08-09  1651.000  1693.800  1709.000  1650.000   47698.00  600519
4767 2021-08-10  1700.000  1799.000  1802.880  1675.000   83285.00  600519
4768 2021-08-11  1780.010  1750.500  1785.010  1750.010   38663.00  600519
4769 2021-08-12  1732.000  1690.000  1749.000  1686.190   47551.00  600519
4770 2021-08-13  1690.000  1700.040  1713.000  1679.000   37905.00  600519
4771 2021-08-16  1696.000  1699.200  1713.600  1685.080   28057.00  600519
4772 2021-08-17  1700.000  1635.000  1700.000  1628.880   61201.00  600519
4773 2021-08-18  1624.660  1620.000  1642.990  1600.000   59970.00  600519
4774 2021-08-19  1622.220  1619.970  1643.200  1600.000   41292.00  600519
4775 2021-08-20  1555.170  1548.000  1597.550  1525.500  114545.00  600519
4776 2021-08-23  1537.880  1570.190  1599.000  1536.770   71597.00  600519
4777 2021-08-24  1575.000  1625.180  1642.550  1565.770   72594.00  600519
4778 2021-08-25  1647.640  1665.020  1680.870  1643.000   54239.00  600519
4779 2021-08-26  1664.990  1595.000  1664.990  1594.720   54020.00  600519
4780 2021-08-27  1589.000  1596.030  1625.000  1584.100   36095.00  600519

[4781 rows x 7 columns]

In [44]:
# 输出收盘价比开盘价上涨3%的日期
# （收盘-开盘）/开盘 > 0.03
((df['close'] - df['open'])/df['open']) > 0.03

date
2001-08-27     True
2001-08-28     True
2001-08-29    False
2001-08-30    False
2001-08-31    False
2001-09-03    False
2001-09-04    False
2001-09-05    False
2001-09-06    False
2001-09-07    False
2001-09-10     True
2001-09-11    False
2001-09-12    False
2001-09-13    False
2001-09-14    False
2001-09-17    False
2001-09-18    False
2001-09-19    False
2001-09-20    False
2001-09-21    False
2001-09-24    False
2001-09-25    False
2001-09-26    False
2001-09-27    False
2001-09-28    False
2001-10-08    False
2001-10-09    False
2001-10-10    False
2001-10-11    False
2001-10-12    False
              ...
2021-07-19    False
2021-07-20    False
2021-07-21    False
2021-07-22    False
2021-07-23    False
2021-07-26    False
2021-07-27    False
2021-07-28     True
2021-07-29    False
2021-07-30    False
2021-08-02     True
2021-08-03    False
2021-08-04    False
2021-08-05    False
2021-08-06    False
2021-08-09    False
2021-08-10     True
2021-08-11    False
2021-08-12    False
2021-08-13    False
2021-08-16    False
2021-08-17    False
2021-08-18    False
2021-08-19    False
2021-08-20    False
2021-08-23    False
2021-08-24     True
2021-08-25    False
2021-08-26    False
2021-08-27    False
Length: 4781, dtype: bool

In [45]:
# 获取了符合条件的行数据
df.loc[((df['close'] - df['open'])/df['open']) > 0.03]

                open     close      high       low     volume    code
date
2001-08-27     5.392     5.554     5.902     5.132  406318.00  600519
2001-08-28     5.467     5.759     5.781     5.407  129647.79  600519
2001-09-10     5.531     5.734     5.757     5.470   18878.89  600519
2001-12-21     5.421     5.604     5.620     5.421    8135.04  600519
2002-01-18     5.437     5.726     5.762     5.421   32262.08  600519
2002-01-31     5.624     5.874     5.937     5.624   40828.30  600519
2003-01-14     4.429     4.611     4.668     4.399    9588.25  600519
2003-10-29     4.132     4.260     4.266     4.132    7084.96  600519
2004-01-05     4.862     5.114     5.124     4.862    8539.75  600519
2004-01-14     5.347     5.593     5.647     5.302   25095.74  600519
2004-01-29     5.424     5.610     5.622     5.424    5353.72  600519
2004-02-26     5.308     5.473     5.478     5.269   10313.48  600519
2004-03-02     5.463     6.031     6.079     5.463   25187.62  600519
2004-03-16     6.474     6.763     6.865     6.414   30957.61  600519
2004-03-24     6.528     6.790     6.819     6.505   13295.74  600519
2004-04-07     7.218     7.530     7.565     7.218   18692.20  600519
2004-04-08     7.536     7.842     7.850     7.501   15913.24  600519
2004-04-30     7.030     7.251     7.264     6.976   12961.66  600519
2004-05-13     7.071     7.321     7.323     7.071   14720.22  600519
2004-07-01     6.357     6.792     6.810     6.355    2781.62  600519
2004-07-05     6.860     7.198     7.211     6.860    5202.29  600519
2004-07-13     7.242     7.478     7.496     7.242    6419.32  600519
2004-07-15     7.511     7.778     7.790     7.511   28186.18  600519
2004-07-23     7.750     7.994     8.004     7.724   10551.81  600519
2004-09-15     7.567     7.915     7.925     7.526   11409.58  600519
2004-09-23     8.159     8.492     8.517     8.159   17667.48  600519
2004-10-19     8.842     9.142     9.198     8.817   10583.64  600519
2004-10-22     9.409     9.948    10.014     9.401   18161.45  600519
2004-11-10     9.655    10.024    10.120     9.655   11288.62  600519
2004-11-25     9.251     9.561     9.676     9.251    5924.14  600519
...              ...       ...       ...       ...        ...     ...
2019-09-18  1108.500  1148.900  1150.000  1108.180   69314.00  600519
2020-02-11  1063.000  1098.000  1099.680  1062.800   47917.00  600519
2020-03-02  1050.110  1086.010  1096.550  1050.010   47663.00  600519
2020-03-05  1136.310  1171.000  1174.990  1130.560   62426.00  600519
2020-03-10  1113.000  1156.000  1168.000  1113.000   58062.00  600519
2020-04-02  1104.000  1145.000  1145.000  1103.880   45206.00  600519
2020-04-22  1206.000  1244.500  1249.500  1202.220   44035.00  600519
2020-05-06  1251.000  1300.000  1300.000  1250.000   35835.00  600519
2020-05-18  1306.000  1346.210  1351.500  1305.130   34362.00  600519
2020-07-02  1499.000  1544.000  1550.900  1495.000   45884.00  600519
2020-07-06  1538.000  1600.000  1616.000  1531.810   51822.00  600519
2020-07-07  1603.090  1688.000  1744.820  1601.000   66664.00  600519
2020-07-13  1714.680  1781.990  1787.000  1714.680   60727.00  600519
2020-12-30  1870.000  1933.000  1933.000  1869.990   34452.00  600519
2021-01-05  1990.000  2059.450  2059.450  1982.460   52116.00  600519
2021-01-12  2088.000  2160.900  2160.900  2085.000   41059.00  600519
2021-01-25  2083.000  2175.000  2179.500  2083.000   55957.00  600519
2021-02-04  2191.000  2320.850  2330.000  2191.000   63851.00  600519
2021-02-09  2368.800  2456.430  2456.430  2350.000   33297.00  600519
2021-02-10  2485.000  2601.000  2601.200  2485.000   61371.00  600519
2021-03-03  2040.000  2140.000  2149.770  2033.000   54215.00  600519
2021-03-05  2000.000  2060.110  2095.000  1988.000   63779.00  600519
2021-03-11  1975.000  2048.000  2079.990  1961.480   56769.00  600519
2021-04-02  2056.000  2162.000  2165.000  2056.000   52028.00  600519
2021-05-11  1876.000  1959.000  1966.000  1873.300   42494.00  600519
2021-05-25  2085.000  2194.500  2200.100  2085.000   67757.00  600519
2021-07-28  1703.000  1768.900  1788.200  1682.120   85369.00  600519
2021-08-02  1664.000  1755.000  1755.980  1620.720   97401.00  600519
2021-08-10  1700.000  1799.000  1802.880  1675.000   83285.00  600519
2021-08-24  1575.000  1625.180  1642.550  1565.770   72594.00  600519

[332 rows x 6 columns]

In [46]:
df.loc[((df['close'] - df['open'])/df['open']) > 0.03].index

DatetimeIndex(['2001-08-27', '2001-08-28', '2001-09-10', '2001-12-21',
               '2002-01-18', '2002-01-31', '2003-01-14', '2003-10-29',
               '2004-01-05', '2004-01-14',
               ...
               '2021-03-03', '2021-03-05', '2021-03-11', '2021-04-02',
               '2021-05-11', '2021-05-25', '2021-07-28', '2021-08-02',
               '2021-08-10', '2021-08-24'],
              dtype='datetime64[ns]', name='date', length=332, freq=None)

In [47]:
# 开盘比前日收盘跌幅超过2%
((df['open'] - df['close'].shift(1)))/df['close'].shift(1) < -0.02

date
2001-08-27    False
2001-08-28    False
2001-08-29    False
2001-08-30    False
2001-08-31    False
2001-09-03    False
2001-09-04    False
2001-09-05    False
2001-09-06    False
2001-09-07    False
2001-09-10    False
2001-09-11    False
2001-09-12     True
2001-09-13    False
2001-09-14    False
2001-09-17    False
2001-09-18    False
2001-09-19    False
2001-09-20    False
2001-09-21    False
2001-09-24    False
2001-09-25    False
2001-09-26    False
2001-09-27    False
2001-09-28    False
2001-10-08    False
2001-10-09    False
2001-10-10    False
2001-10-11    False
2001-10-12    False
              ...
2021-07-19    False
2021-07-20    False
2021-07-21    False
2021-07-22    False
2021-07-23    False
2021-07-26    False
2021-07-27    False
2021-07-28    False
2021-07-29    False
2021-07-30    False
2021-08-02    False
2021-08-03    False
2021-08-04    False
2021-08-05    False
2021-08-06    False
2021-08-09    False
2021-08-10    False
2021-08-11    False
2021-08-12    False
2021-08-13    False
2021-08-16    False
2021-08-17    False
2021-08-18    False
2021-08-19    False
2021-08-20     True
2021-08-23    False
2021-08-24    False
2021-08-25    False
2021-08-26    False
2021-08-27    False
Length: 4781, dtype: bool

In [53]:
df.loc[((df['open'] - df['close'].shift(1)))/df['close'].shift(1) < -0.02].index

DatetimeIndex(['2001-09-12', '2002-06-26', '2002-12-13', '2004-07-01',
               '2004-10-29', '2006-08-21', '2006-08-23', '2007-01-25',
               '2007-02-01', '2007-02-06', '2007-03-19', '2007-05-21',
               '2007-05-30', '2007-06-05', '2007-07-27', '2007-09-05',
               '2007-09-10', '2008-03-13', '2008-03-17', '2008-03-25',
               '2008-03-27', '2008-04-22', '2008-04-23', '2008-04-29',
               '2008-05-13', '2008-06-10', '2008-06-13', '2008-06-24',
               '2008-06-27', '2008-08-11', '2008-08-19', '2008-09-23',
               '2008-10-10', '2008-10-15', '2008-10-16', '2008-10-20',
               '2008-10-23', '2008-10-27', '2008-11-06', '2008-11-12',
               '2008-11-20', '2008-11-21', '2008-12-02', '2009-02-27',
               '2009-03-25', '2009-08-13', '2010-04-26', '2010-04-30',
               '2011-08-05', '2012-03-27', '2012-08-10', '2012-11-22',
               '2012-12-04', '2012-12-24', '2013-01-16', '2013-01-25',
               '2013-09-02', '2014-04-25', '2015-01-19', '2015-05-25',
               '2015-07-03', '2015-07-08', '2015-07-13', '2015-08-24',
               '2015-09-02', '2015-09-15', '2017-11-17', '2018-02-06',
               '2018-02-09', '2018-03-23', '2018-03-28', '2018-07-11',
               '2018-10-11', '2018-10-24', '2018-10-25', '2018-10-29',
               '2018-10-30', '2019-05-06', '2019-05-08', '2019-10-16',
               '2020-01-02', '2020-02-03', '2020-03-13', '2020-03-23',
               '2020-10-26', '2021-02-26', '2021-03-04', '2021-04-28',
               '2021-08-20'],
              dtype='datetime64[ns]', name='date', freq=None)

In [55]:
# 从10年1月1日开始，每月第一个交易日，每年最后一个交易日卖出
new_df = df['2010':'2021']
new_df

                open     close      high       low     volume    code
date
2010-01-04   109.760   108.446   109.760   108.044   44304.88  600519
2010-01-05   109.116   108.127   109.441   107.846   31513.18  600519
2010-01-06   107.840   106.417   108.165   106.129   39889.03  600519
2010-01-07   106.417   104.477   106.691   103.302   48825.55  600519
2010-01-08   104.655   103.379   104.655   102.167   36702.09  600519
2010-01-11   104.400   102.926   105.230   102.422   24461.03  600519
2010-01-12   103.028   105.708   106.040   102.492   31063.40  600519
2010-01-13   104.649   103.022   105.389   102.741   37924.44  600519
2010-01-14   103.379   107.552   107.974   103.379   46454.64  600519
2010-01-15   107.533   108.401   110.641   107.533   45938.50  600519
2010-01-18   108.484   109.110   109.926   108.420   21461.53  600519
2010-01-19   109.116   108.337   109.441   108.165   17818.91  600519
2010-01-20   108.427   105.881   108.580   105.804   20972.95  600519
2010-01-21   105.842   106.397   107.450   105.613   17257.48  600519
2010-01-22   106.314   104.738   106.755   103.309   25432.94  600519
2010-01-25   104.560   105.957   106.761   103.704   23239.15  600519
2010-01-26   107.380   106.378   108.593   105.038   32889.16  600519
2010-01-27   105.951   104.643   107.068   104.400   19316.57  600519
2010-01-28   104.566   107.974   108.708   104.336   30267.52  600519
2010-01-29   108.452   107.552   108.612   107.004   37172.82  600519
2010-02-01   107.769   107.776   108.216   106.576   29655.94  600519
2010-02-02   107.208   106.263   108.484   106.117   15493.53  600519
2010-02-03   106.066   105.887   107.272   104.783   23034.65  600519
2010-02-04   105.868   107.591   108.006   105.376   22475.33  600519
2010-02-05   106.959   109.282   109.684   106.570   26234.30  600519
2010-02-08   109.282   109.269   112.058   108.816   31496.10  600519
2010-02-09   109.760   109.193   110.609   108.822   14151.24  600519
2010-02-10   109.760   109.652   110.137   108.931    6398.14  600519
2010-02-11   109.633   110.641   111.318   109.505   14945.05  600519
2010-02-12   111.018   110.456   111.164   109.888    9346.40  600519
...              ...       ...       ...       ...        ...     ...
2021-07-19  1955.890  1975.000  1986.000  1941.000   30052.00  600519
2021-07-20  1975.000  1980.000  1988.930  1961.410   23475.00  600519
2021-07-21  1989.000  1969.000  2006.000  1962.010   29780.00  600519
2021-07-22  1960.000  1940.010  1973.900  1938.960   39090.00  600519
2021-07-23  1937.820  1900.000  1937.820  1895.090   47585.00  600519
2021-07-26  1879.000  1804.110  1879.000  1780.000   98619.00  600519
2021-07-27  1803.000  1712.890  1810.000  1703.000   86577.00  600519
2021-07-28  1703.000  1768.900  1788.200  1682.120   85369.00  600519
2021-07-29  1810.010  1749.790  1823.000  1734.340   63864.00  600519
2021-07-30  1725.000  1678.990  1725.000  1657.760   77736.00  600519
2021-08-02  1664.000  1755.000  1755.980  1620.720   97401.00  600519
2021-08-03  1730.000  1749.300  1768.990  1688.800   54375.00  600519
2021-08-04  1734.060  1724.000  1760.000  1718.000   38175.00  600519
2021-08-05  1692.880  1699.000  1745.000  1676.360   48060.00  600519
2021-08-06  1689.000  1671.000  1694.010  1646.600   45686.00  600519
2021-08-09  1651.000  1693.800  1709.000  1650.000   47698.00  600519
2021-08-10  1700.000  1799.000  1802.880  1675.000   83285.00  600519
2021-08-11  1780.010  1750.500  1785.010  1750.010   38663.00  600519
2021-08-12  1732.000  1690.000  1749.000  1686.190   47551.00  600519
2021-08-13  1690.000  1700.040  1713.000  1679.000   37905.00  600519
2021-08-16  1696.000  1699.200  1713.600  1685.080   28057.00  600519
2021-08-17  1700.000  1635.000  1700.000  1628.880   61201.00  600519
2021-08-18  1624.660  1620.000  1642.990  1600.000   59970.00  600519
2021-08-19  1622.220  1619.970  1643.200  1600.000   41292.00  600519
2021-08-20  1555.170  1548.000  1597.550  1525.500  114545.00  600519
2021-08-23  1537.880  1570.190  1599.000  1536.770   71597.00  600519
2021-08-24  1575.000  1625.180  1642.550  1565.770   72594.00  600519
2021-08-25  1647.640  1665.020  1680.870  1643.000   54239.00  600519
2021-08-26  1664.990  1595.000  1664.990  1594.720   54020.00  600519
2021-08-27  1589.000  1596.030  1625.000  1584.100   36095.00  600519

[2828 rows x 6 columns]

+ 每月买入

    + 每年12次买入，买入1200股，以当期的开盘价进行股票的买卖
    + 一个完整的年，需要卖出1200支股票，以开盘价为单价
    + 2021年只可以买，不可以卖，但是手里剩余的股票需要计算到总收益中